_base_: bases/mednext.yaml
experiment_name: fiber_umich_CA1-2_2
description: Inference on full 87-slice CA1-1-1-2 using CA1-2_2 fine-tuned model

system:
  training:
    num_gpus: 1
    num_cpus: 8
    num_workers: 8
    batch_size: 4
  inference:
    num_cpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42

model:
  out_channels: 3
  input_size:
  - 32
  - 96
  - 96
  output_size:
  - 32
  - 96
  - 96
  mednext_size: S
  mednext_kernel_size: 3
  deep_supervision: false
  loss_functions:
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedMSELoss
  loss_weights:
  - 4.0
  - 2.0
  - 1.0
  - 0.5
  - 2.0
  loss_kwargs:
  - reduction: mean
    pos_weight: 20.0
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - reduction: mean
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - tanh: true
  multi_task_config:
  - - 0
    - 1
    - binary
    - - 0
      - 1
  - - 1
    - 2
    - instance_boundary
    - - 2
      - 3
  - - 2
    - 3
    - skeleton_aware_edt
    - - 4

data:
  train_image:
  - /projects/weilab/dataset/barcode/2026/umich/0112-5-CA1-2_2.tif
  train_label:
  - /projects/weilab/dataset/barcode/2026/umich/seg 0112-5-CA1-2_2_Mehul.tif
  train_resolution:
  - 40
  - 16
  - 16
  use_preloaded_cache: true
  persistent_workers: false
  patch_size:
  - 32
  - 96
  - 96
  iter_num_per_epoch: 1000
  image_transform:
    clip_percentile_low: 0.005
    clip_percentile_high: 0.995
    pad_size:
    - 8
    - 16
    - 16
    pad_mode: reflect
  label_transform:
    targets:
    - name: binary
      kwargs: {}
    - name: instance_boundary
      kwargs:
        thickness: 1
        edge_mode: all
        mode: 2d
    - name: skeleton_aware_edt
      kwargs:
        resolution:
        - 40
        - 16
        - 16
        alpha: 1
        bg_value: -1.0
        relabel: true

test:
  data:
    test_image:
    - /projects/weilab/dataset/barcode/2026/test_shock0202/0112-5-CA1-1-1-2.tif
    test_resolution:
    - 40
    - 16
    - 16

inference:
  sliding_window:
    window_size:
    - 32
    - 256
    - 256
    stride:
    - 16
    - 128
    - 128
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: reflect
    pad_size:
    - 16
    - 32
    - 32
  test_time_augmentation:
    enabled: true
    channel_activations:
    - - 0
      - 1
      - sigmoid
    - - 1
      - 2
      - sigmoid
    - - 2
      - 3
      - tanh
  decoding:
  - name: decode_instance_binary_contour_distance
    kwargs:
      binary_threshold:
      - 0.7112534296035813
      - 0.0023967858292893787
      contour_threshold:
      - 0.7430296129955649
      - 1.0428413961368097
      distance_threshold:
      - -0.7298771516024907
      - -0.6837897682233834
      min_instance_size: 1900
      min_seed_size: 39
  evaluation:
    enabled: false
