_base_: bases/mednext.yaml
experiment_name: fiber_retrain_all
description: Inference on 4 multi-region volumes (A1-2002, A1-2003 s01/s02, A1-2007)

system:
  inference:
    num_cpus: 4
    num_workers: 4
    batch_size: 1
  seed: 42

model:
  out_channels: 3
  input_size:
  - 32
  - 96
  - 96
  output_size:
  - 32
  - 96
  - 96
  mednext_size: S
  mednext_kernel_size: 3
  deep_supervision: false
  loss_functions:
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedMSELoss
  loss_weights:
  - 4.0
  - 2.0
  - 1.0
  - 0.5
  - 2.0
  loss_kwargs:
  - reduction: mean
    pos_weight: 20.0
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - reduction: mean
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - tanh: true
  multi_task_config:
  - - 0
    - 1
    - binary
    - - 0
      - 1
  - - 1
    - 2
    - instance_boundary
    - - 2
      - 3
  - - 2
    - 3
    - skeleton_aware_edt
    - - 4

data:
  image_transform:
    clip_percentile_low: 0.005
    clip_percentile_high: 0.995

test:
  data:
    test_image:
    - /projects/weilab/dataset/barcode/2026/umich/processed_ch1/A1-2002_ch1.tif
    - /projects/weilab/dataset/barcode/2026/umich/processed_ch1/A1-2003_s01_ch1.tif
    - /projects/weilab/dataset/barcode/2026/umich/processed_ch1/A1-2003_s02_ch1.tif
    - /projects/weilab/dataset/barcode/2026/umich/processed_ch1/A1-2007_ch1.tif
    image_transform:
      normalize: "0-1"
      clip_percentile_low: 0.005
      clip_percentile_high: 0.995

inference:
  sliding_window:
    window_size:
    - 32
    - 256
    - 256
    stride:
    - 16
    - 128
    - 128
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: reflect
    pad_size:
    - 16
    - 32
    - 32
  test_time_augmentation:
    enabled: true
    channel_activations:
    - - 0
      - 1
      - sigmoid
    - - 1
      - 2
      - sigmoid
    - - 2
      - 3
      - tanh
  decoding:
  - name: decode_instance_binary_contour_distance
    kwargs:
      binary_threshold:
      - 0.7503891044149624
      - 0.0046306263327246
      contour_threshold:
      - 0.48708101851244906
      - 1.025119772551816
      distance_threshold:
      - -0.6695257662389609
      - -0.07270575159140885
      min_instance_size: 100
      min_seed_size: 40
  save_prediction:
    output_formats:
    - h5
    - tiff
  evaluation:
    enabled: false
